task_organizer/config/routes.rb
Rails.application.routes.draw do

  get 'graveyard/index'
  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/about'

  resources :improvements
  resources :comments
  resources :users
 

  root 'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'cemiterio' => 'graveyard#index',:as => :cemiterio

end

task_organizer/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  before_save { self.sub_name = sub_name.upcase }
  validates :sub_name, presence: true, length: {is: 2}
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :comments
  has_many :improvements
  has_many :import_logs


  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end
  end




  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

task_organizer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :only_logged, except: [:create,:new, :index]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  include ApplicationHelper
  helper_method :sort_column, :sort_direction

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end




  # GET /users/1
  # GET /users/1.json
  def show
    all_status = Status.get_all_status
    @improvements = Improvement.search(params[:search]).where("(responsible_id = ?) AND status_id != 3", current_user.id)
                        .where("status_id in (?)", params[:status] || all_status)
                        .order(sort_column + " " + sort_direction)
                        .paginate(:per_page => 10, :page => params[:page])

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuário foi cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to improvements_path, notice: 'Usuário foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

#####################################################################

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :permission, :sub_name, :admin)
    end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || is_admin?
  end

  private
      # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def sort_column
    Improvement.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end



end

task_organizer/app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

task_organizer/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= f.label :nome %>
            <%= f.text_field :name %>

            <%= f.label :email %>
            <%= f.email_field :email %>

            <%= f.label :iniciais %>
            <%= f.text_field :sub_name %>

            <%= f.label :senha %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "Confirmação" %>
            <%= f.password_field :password_confirmation %>

            <%= f.submit "Criar minha conta", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
<% end %>

task_organizer/app/views/users/_show.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th= sortable "title", "Título"
      %th Categoria
      %th Conteúdo
      %th= sortable "user_id", "Criado por"
      %th= sortable "user_id", "Responsável"
      %th= sortable "created_at", "Criado em"
      %th= sortable "updated_at", "Atualizado em"
      %th= sortable "status_id", "Status"
      %th= sortable "", "Ultima atualização em"
      %th{:colspan => "3"}
  %tbody{:id => "all_improvements"}
  - improvements.each do |improvement|
    %tr{:class => improvement.status ? improvement.status.get_class : 1 }
      %td= improvement.title
      %td= improvement.category
      %td= improvement.content
      %td= improvement.name
      %td= improvement.responsible.name
      %td= improvement.created_at.to_datetime.strftime("%d/%m/%Y %H:%M")
      %td= improvement.updated_at.to_datetime.strftime("%d/%m/%Y %H:%M")
      %td= improvement.status.name
      %td= distance_of_time_in_words(improvement.updated_at, improvement.created_at) 
      %form


      %td
        =link_to 'Exibir', improvement, class: "btn btn-primary btn-go btn-table"
        - if current_user.id == improvement.user_id || current_user.admin?
          = link_to 'Editar', edit_improvement_path(improvement), class: "btn btn-primary btn-go btn-table"
          = link_to 'Deletar', improvement, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-go btn-table"

task_organizer/app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row edit">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= f.label :nome %>
            <%= f.text_field :name %>

            <%= f.label :email %>
            <%= f.email_field :email %>

            <%= f.label :iniciais %>
            <%= f.text_field :sub_name %>

            <%= f.label :senha %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "Confirmação" %>
            <%= f.password_field :password_confirmation %>
            <% if current_user.admin? && !current_user?(@user) %>
            <%= f.label :permission, "Permissão" %>
            <%= f.collection_radio_buttons :permission, [[true, 'Sim'] ,[false, 'Não']], :first, :last %>
            <% end %>
            <br>
            <br>
            <% if current_user.admin? && !current_user?(@user) %>
                <%= f.label :admin, "Administrador" %>
                <%= f.collection_radio_buttons :admin, [[true, 'Sim'] ,[false, 'Não']], :first, :last %>
            <% end %>

            <%= f.submit "Salvar Mudanças", class: "btn btn-primary" %>
        <% end %>
        <div class="gravatar_edit">
          <%= gravatar_for @user %>
          <a href="http://gravatar.com/emails" target="_blank">Mudar</a>
      </div>
    </div>
</div>
<% end %>

task_organizer/app/views/users/index.html.erb
<h1>Usuários</h1>
<center>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Deletar', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<br>

task_organizer/app/views/users/new.html.erb
<h1>Novo Usuário</h1>

<%= render 'form' %>

task_organizer/app/views/users/show.html.haml
- provide(:title, @user.name)
.col-md-12
  .col-md-2
    .row
      %aside
        %section.user_info
          %h1
            = gravatar_for @user
            = @user.name
    %p
      %strong Nome:
      = @user.name
    %p
      %strong Email:
      = @user.email
    %br/
    %form
      %p
        %strong Status:
      = form_tag improvements_path, :method => 'get' do
        - all_status = params["status"]
        - Status.all.each_with_index do |status,i|
          = check_box_tag "status[]", status.id, all_status && all_status.include?((i + 1).to_s)
          = "#{status.name}"
        %p
          %br/
          = text_field_tag :search, params[:search] , placeholder: params[:search]
          = submit_tag "Buscar", :title => nil,class: "btn btn-primary btn-go"
  .col-md-10
    %h1 Minhas Tarefas
    %br/
    %br/
    = will_paginate @improvements
    %div{:id => "improvements"}
      = render :partial => "show", :locals => {:improvements => @improvements}
    = will_paginate @improvements
    %br/