desafio-programacao-1b-master/config/routes.rb
Rails.application.routes.draw do
  resources :pedidos, :path => "vendas"
  resources :import_files,  only: [:new, :create]
  root "pedidos#index"

end

desafio-programacao-1b-master/app/models/comprador.rb
class Comprador < ActiveRecord::Base
    has_many :pedidos
    belongs_to :endereco
end

desafio-programacao-1b-master/app/models/endereco.rb
class Endereco < ActiveRecord::Base
    has_many :comprador
end

desafio-programacao-1b-master/app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
    belongs_to :pedido
end

desafio-programacao-1b-master/app/models/import_file.rb
class ImportFile < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader
    validates :attachment, presence: true
end

desafio-programacao-1b-master/app/models/pedido.rb
class Pedido < ActiveRecord::Base
    belongs_to :produto
    belongs_to :comprador
end

desafio-programacao-1b-master/app/models/produto.rb
class Produto < ActiveRecord::Base
   belongs_to :fornecedor
   has_many :pedidos
end

desafio-programacao-1b-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

desafio-programacao-1b-master/app/controllers/import_files_controller.rb
class ImportFilesController < ApplicationController

require 'base64'
require 'csv'

  def new
   @import_file = ImportFile.new
  end

  def create
    
    # Processo de ETL para carregar os dados para o banco de dados relacional
    
    @import_file = ImportFile.new(import_file_params)
    
      uploaded_file = @import_file.attachment
      file_content = uploaded_file.path
      
    if !file_content.blank?
      
      File.open(file_content) do |f|
        CSV.foreach(f,:headers => true, col_sep:"\t") do |row|
          
          #Carregando a tabela Fornecedors    	         
          Fornecedor.where(nome: row['Fornecedor'])
                    .first_or_create(nome: row['Fornecedor'] )
          
          #Carregando a tabela Enderecos    
          Endereco.where(descricao: row['Endereço'])
                  .first_or_create(descricao: row['Endereço'] )
          
              
          endereco = Endereco.where("descricao = ?", row['Endereço']).first
          
          #Carregando a tabela Compradors    	         
          Comprador.where(nome: row[0],
                          endereco_id: endereco.id)
                          .first_or_create(nome: row[0],
                          endereco_id: endereco.id)
              
          fornecedor = Fornecedor.where("nome = ?", row['Fornecedor']).first
                          
          #Carregando a tabela Produtos                 
          Produto.where(descricao: row['descrição'],
                        fornecedor_id: fornecedor.id,
                        preco_unit: row['Preço Uniário'])
                        .first_or_create(descricao: row['descrição'],
                        fornecedor_id: fornecedor.id,
                        preco_unit: row['Preço Uniário'])
              
          produto = Produto.where("descricao = ?", row['descrição'] )
                           .where("preco_unit = ?", row['Preço Uniário']).first
              
          comprador = Comprador.where("nome = ?", row[0])
          	                   .where("endereco_id = ?", endereco.id).first
          
          #Carregando a tabela Pedidos    
          Pedido.create ({:quantidade => row['Quantidade'],
              	          :produto_id => produto.id,
              	          :comprador_id => comprador.id} )
              
             
          end
      end
    end      
    if @import_file.save
      redirect_to pedidos_path, notice:  "Arquivo Importado com Sucesso"
    else 
       render "new"
    end
    
  end


private

   def import_file_params
      params.fetch(:import_file, {}).permit(:attachment)
   end
   
    
end
       
   

desafio-programacao-1b-master/app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]


  def index
    @pedidos = Pedido.all
    @receita_bruta = Pedido.includes(:produto).sum(:preco_unit)
  end

 
end

desafio-programacao-1b-master/app/helpers/application_helper.rb
module ApplicationHelper
end

desafio-programacao-1b-master/app/helpers/import_files_helper.rb
module ImportFilesHelper
end

desafio-programacao-1b-master/app/helpers/pedidos_helper.rb
module PedidosHelper
end

desafio-programacao-1b-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   
   <head>
      <title>Desafio Héttori Tosi</title>
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
   </head>
   
   <body>
     
         <%= yield %>
    
   </body>

</html>

desafio-programacao-1b-master/app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<div class="new_file">
<%= link_to 'Importar Novo Arquivo', new_import_file_path, class: "btn btn-primary"  %>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Descrição</th>
      <th>Preço Unitário</th>
      <th>Quantidade</th>
      <th>Endereço</th>
      <th>Fornecedor</th>
     
    </tr>
  </thead>

  <tbody>
    
    <% @pedidos.each do |pedido| %>
  
    <tr>
        <td><%= pedido.comprador.nome %></td>
        <td><%= pedido.produto.descricao %></td>
        <td><%= pedido.produto.preco_unit %></td>
        <td><%= pedido.quantidade %></td> 
        <td><%= pedido.comprador.endereco.descricao %></td>
       <td><%= pedido.produto.fornecedor.nome %></td>
    <% end %>
   </tr>
   
  
  
  </tbody>

</table>
  <h2>Total da Receita Bruta R$  <%= @receita_bruta %></h2>

<br>


<%= link_to 'Importar Novo Arquivo', new_import_file_path, class: "btn btn-primary"  %>