evolution_of_improvements/config/routes.rb
Rails.application.routes.draw do

  get 'graveyard/index'
  get 'improvements/mobile' => 'improvements#index_mobile', via: [:options]
  get 'improvements/mobile/:id' => 'improvements#update_mobile', via: [:options]
  get 'sessions/new'

  get 'static_pages/home'

  get 'static_pages/about'

  resources :improvements
  resources :comments
  resources :users
  resources :import_logs do
    collection do
      get :ajax_import_log
    end
  end

  root 'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'improvements/new' => 'improvements#create_mobile', via: [:options]
  post   'login/mobile'   => 'sessions#create_mobile'
  get 'cemiterio' => 'graveyard#index',:as => :cemiterio

end

evolution_of_improvements/app/views/layouts/_footer.erb
<footer class="footer col-md-12">
  <small>
    por Héttori Tosi em  <a href="http://www.studiare.com.br/">Studiare</a> | versão 3.2.0
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre", about_path  %></li>
    </ul>
  </nav>
</footer>

evolution_of_improvements/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
    /[if lt IE 9]
  %script{:src => "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"}
  %body
    %header
      %nav.navbar.navbar-custom.navbar-fixed-top.improv{:role => "navigation"}
        .container
          .navbar-header
            %a.logo.page-scroll{:href => root_path}
              = image_tag "studiare_logo.png"
            %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          .collapse.navbar-collapse.navbar-right.navbar-main-collapse
            %ul.nav.navbar-nav
              - if logged_in?
                %li.dropdown
                  %a{:href=>"#", :class=>"dropdown-toggle", "data-toggle"=>"dropdown"}Tarefas<b class="caret"></b>
                  %ul.dropdown-menu
                    %li.c2
                      = link_to "Todas as Tarefas", improvements_path
                    %li.c2
                      = link_to "Minhas Tarefas", current_user
                    %li.c2
                      = link_to "Cemitério", cemiterio_path
                %li
                  = link_to "Nova Tarefa", new_improvement_path
                %li
                  = link_to "Configurações", edit_user_path(current_user)
                %li
                  = link_to "Usuários", users_path if is_admin?
                %li
                  = link_to "Importar CSV", new_import_log_path if is_admin?
                %li
                  %a.page-scroll{:href => about_path} Sobre
                %li
                  = link_to "Sair", logout_path, method: "delete"
              -else
                %li
                  %a.page-scroll{:href => about_path} Sobre
                %li
                  %a.page-scroll{:href => 'sessions/new' } Entrar
    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'